require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6.3
  DisplayCopNames: true
  Exclude:
    - 'db/schema.rb'

# RAILS #######################################################################

Rails:
  Enabled: true

# STYLES ######################################################################

Bundler/OrderedGems:
  Enabled: true

Style/Documentation:
  Enabled: false
