version: '3.6'

services:
  generator:
    stdin_open: true
    tty: true
    env_file: .env
    build:
      context: .
      args:
        - USER
        - UID
        - APP_NAME
    command: 'bash'
    volumes:
      - .:/rails
