version: '3.6'

x-default: &default
  env_file: .env
  depends_on:
    - db
    - redis
  entrypoint: './entrypoint.sh'
  environment:
    REDIS_URL: redis://redis:6379
  stdin_open: true
  tty: true
  volumes:
      - .:/#{app_name}
  links:
    - db
services:
  web:
    <<: *default
    build:
      context: .
      args:
        - USER
        - UID
    command: './bin/rails server -b 0.0.0.0 -p 3000 --pid /tmp/rails_server.pid'
    ports:
      - '3000:3000'
    extra_hosts:
      - '#{app_name}.doghero.local: 127.0.0.1'
  db:
    image: postgres:12.0
    environment:
      POSTGRES_USER: #{app_name}
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes:
      - redis-data:/data
volumes:
  pgdata:
  redis-data:
